name: deploy-netlify

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      - run: npm install -g yarn
      - run: yarn

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=docs/.vitepress/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
