name: deploy-test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build Image
    uses: onedongbing/gh-actions/.github/workflows/build-image.yml@master
    secrets:
      WORKFLOW_SECRET: ${{ secrets.WORKFLOW_SECRET }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    with:
      platforms: linux/amd64
      push: true
      tags: wangdongbing/notebooks:test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            echo '开始执行部署任务'
            rm -rf ~/gh-projects/notebooks
            git clone "https://github.com/onedb-document/notebooks.git" ~/gh-projects/notebooks
            cd ~/gh-projects/notebooks
            echo '仓库准备完毕，启动服务'
            docker-compose up -d --pull always
            echo '运行成功'
