name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0

      - # https://github.com/docker/setup-buildx-action/issues/57#issuecomment-1059657292
        # https://github.com/docker/buildx/issues/136#issuecomment-550205439
        # docker buildx create --driver-opt --driver-opt --driver-opt
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            wangdongbing/notebooks:latest
            wangdongbing/notebooks:0.1.0
            wangdongbing/notebooks:0.1
            wangdongbing/notebooks:0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/remote.key
          chmod 600 ~/.ssh/remote.key
          cat >>~/.ssh/config <<END
          Host remote
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/remote.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.REMOTE_SSH_HOST }}
          SSH_USER: ${{ secrets.REMOTE_SSH_USER }}
          SSH_KEY: ${{secrets.REMOTE_SSH_KEY}}

      - name: deploy
        run: |
          ssh remote 'curl -s "https://raw.githubusercontent.com/onedb-document/notebooks/master/.github/deploy.sh" | bash'
