name: deploy-netlify

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '18'

      - # 这里注意下ubuntu cp命令的区别，不然dist目录本身会被拷贝进去
        name: Build
        run: |
          npm install -g yarn
          yarn
          yarn docs:build
          mkdir -p public/notebooks
          cp -R -i docs/.vitepress/dist/* public/notebooks/
          ls public/notebooks

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
